### ISSUE TITLE
Potentail typo in app.py

### ISSUE THREAD

**Issue by ritchey0713** [learn-co-curriculum/python-p4-building-get-api#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208451?module_item_id=480484

### Concern

Error triggered: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

when directly following instructions ran into this error, it is easy to fix by changing the database uri from 'sqlite:///db/app.db' to 'sqlite:///app.db'

**Comment by professor-ben** [comment]
Hey y'all, quick fix while I make this change: delete `db/` from the database path. SQLAlchemy has some issues with navigating through certain directories with sqlite, so creating it in the server/lib directory is the best approach.

**Comment by professor-ben** [comment]
This turned out to be another Canvas sync issue. I'll make sure to push up unsynced changes manually later today.
