### ISSUE TITLE
Issues creating database file on "Building a GET API" Lesson

### ISSUE THREAD

**Issue by jacoblogan98** [learn-co-curriculum/python-p4-building-get-api#2]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208451?module_item_id=480484

### Concern

I was getting a lengthy error when trying to run the "flask db upgrade" command as instructed by the lab. After changing line 12 of the app.py file to "app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'", it fixed the error and ran the migrations. Originally, the database URI is being set to 'sqlite:///db/app.db'. I've also been running into issues with dependencies on all of these Flask labs, with a recurring error that reads: "ModuleNotFoundError: No module named 'importlib_metadata'". After running: "pip install importlib_metadata' everything runs as intended.

**Comment by professor-ben** [comment]
These are a couple legacy issues- I'll have them straightened out for this lesson shortly. Apologies if you see the importlib business again- we're working on finishing those out in Phase 4.

**Comment by professor-ben** [comment]
These should be fixed with a couple pushes from this morning. Thanks for reporting!

-Ben
