### ISSUE TITLE
Running seed.py

### ISSUE THREAD

**Issue by jeryelblanco** [learn-co-curriculum/python-p4-building-get-api#3]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208451?module_item_id=480484

### Concern

Issue when running "python seed.py" in terminal. 
Error Message:
  File "seed.py", line 68, in <module>
    db.init_app(app)
  File "/Users/jeryelblanco/.local/share/virtualenvs/python-p4-building-get-api-kiJ69zp2/lib/python3.8/site-packages/flask_sqlalchemy/extension.py", line 253, in init_app
    raise RuntimeError(
RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.

Solution: Comment out line 68

**Comment by schnyle** [comment]
Agreed: this is a repeated issue for the phase-4 curriculum

**Comment by professor-ben** [comment]
This is fixed now- `db.init_app()` does not need to be run in modules that import `app` from `app.py`.

Thanks,
Ben
