### ISSUE TITLE
SQLAlchemy database path incorrect

### ISSUE THREAD

**Issue by schnyle** [learn-co-curriculum/python-p4-building-get-api#4]
### Canvas Link

https://learning.flatironschool.com/courses/6259/assignments/233439?module_item_id=547397

### Concern

app.py line 12 contains a non-existent path:
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db/app.db'

should be 
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'

**Comment by professor-ben** [comment]
Thanks for letting us know- this is fixed now.

-Ben

**Comment by professor-ben** [comment]
Thanks for letting us know- this is fixed now.

-Ben
