### ISSUE TITLE
Debug.py import not working.

### ISSUE THREAD

**Issue by connork97** [learn-co-curriculum/python-p4-building-get-api#6]
### Canvas Link

https://learning.flatironschool.com/courses/6275/assignments/237675?module_item_id=558419

### Concern

In the "Accessing Associated Data" section, we added "SerialMixin" and were told to run "python debug.py" and run the following two commands:
game = Game.query.first()
game.to_dict()

However, instead of the shown response we get "NameError: name 'Game' is not defined."  This effectively makes us either import 
'Game' from models directly in the debugger, or remove the line of code "with app.app_context():" from debug.py and bring the ipdb in one indentation level.  I don't recall covering why "with app.app_context()" would imped the debugger, and the issue arose without changing the debug.py file at all since I was not explicitly told to do so.

### Suggested Changes

If there are additional steps to alter debug.py, please add them.  Otherwise if the issue is due to the "with app.app_context()" line of code, either alter or remove that as needed.

**Comment by professor-ben** [comment]
Hi Connor,

Thanks for the report! This has been a confusing issue so far that seems to appear in this lesson but not others with the same code behind them. I'll keep looking into potential causes for `app.app_context()` to be failing here.

-Ben

**Comment by connork97** [comment]
Hi Ben,

This same issue has occurred on multiple occasions.  My group just ran into it again on the python-p4-validation-flask-sqlalchemy-validations-lab.  I don't recall the specific labs otherwise but I do remember the issue popping up more than just these two times.  Just an FYI!

Thanks,

~Connor

**Comment by professor-ben** [comment]
Ah, that's good to know. Less confusing, in a way.

In the meantime, try deleting that line from debug.py and running queries inside of a `with app.app_context()` block in the debugger. It's obviously not a perfect solution, but it should work in the meantime.

-Ben

**Comment by professor-ben** [comment]
Better advice: use `flask shell` and run your imports manually. I wanted to set things up this way so that imports were taken care of for you, but avoiding context grief is likely more valuable.

**Comment by professor-ben** [comment]
Hi again Connor,

I've made the decision to just move Phase 4 over to using the Flask shell in place of these debug.py files. That change should be reflected in most lessons fairly soon. You might not see them on Canvas, but the instructions will be updated in the GitHub repos.

Thanks again for reporting,
Ben
